### ISSUE TITLE
GET /items

### ISSUE THREAD

**Issue by pmx625** [sinfo/deck2#100]
**Path:** /items

**Method:** GET

**Auth:** MEMBER

**Query:**

- `name={String}` name of the item
- `type={String}` type of the item
- `price={Number}` price of the item
- `vat={Number}` vat of the item

**Response:**

```javascript
[{
  id: String,
  name: String,
  type: String,
  description: String,
  img: String,
  price: Number // €,
  vat: Number // %
}]
```

**Notes:**

Returns all items by default.

**Status codes:**

| Code | Rule    |
|------|---------|
| 400 | Bad query |
| 200 | Always |

**Tests:**

1. No query

Should return all the items.

2. Name on query

Should return all the items with the specific name.

3. Type on query

Should return all the items with the specific type.

4. Price on query

Should return all the items with the specific query.

5. Vat on query

Should return all the items with the specific vat.

6. Bad query

- Bad price (Price is not a number): Should return a 400 status code.
- Bad vat (Vat is not a number): Should return a 400 status code.

**Comment by fchamicapereira** [comment]
Add type, price and vat query.
You mention 400 as a possible status code, however none of the tests reflect that. Because the price is a number, a "bad query" would be the given price on the query not being a number. Same goes for vat.
