### ISSUE TITLE
PUT /packages/{id}/items

### ISSUE THREAD

**Issue by pmx625** [sinfo/deck2#101]
**Path:** /packages/{id}/items

**Method:** POST

**Auth:** COORDINATOR

**Parameters:**

- `id={String}`

**Payload:**

```javascript
{
  items: [{ item: Item, quantity: Number }]
}
```

**Response:**

```javascript
{
  id: String,
  name: String,
  items: [{ item: Item, quantity: Number }],
  price: Number,
  vat: Number
}
```
**Notes:** 
`id` corresponds to an `_id` index of mongodb.
Creates a new item in a package.

**Status codes:**

| Code | Rule    |
|------|---------|
| 404 | Object not found |
| 400 | Invalid payload |
| 200 | Always |

**Tests:**

1. Missing field on payload
Should return a 400 status code.

2. Invalid field on payload
Should return a 400 status code.

3. No package with id
Should return a 404 status code.

4. Valid payload
Should return the new item.

**Comment by fchamicapereira** [comment]
You don't create items without a context.

examples:
- https://github.com/sinfo/deck2/issues/76
- https://github.com/sinfo/deck2/issues/93

Items are created in the context of a event, and/or a package.

**Comment by fchamicapereira** [comment]
Response object is missing the `id`.
The payload is missing the `quantity`, necessary for the package's item.
The response object should not be an item, but the modified package.
