### ISSUE TITLE
PUT /items/{id}

### ISSUE THREAD

**Issue by pmx625** [sinfo/deck2#102]
**Path:** /items/{id}

**Method:** PUT

**Auth:** COORDINATOR

**Parameters:**

- `id={String}`

**Payload:**

```javascript
{
  name: String,
  type: String,
  description: String,
  img: String,
  price: Number // €,
  vat: Number // %
}
```

**Response:**

```javascript
{
  id: String,
  name: String,
  type: String,
  description: String,
  img: String,
  price: Number // €,
  vat: Number // %
}
```
**Notes:**
Changes an items matching `name`, inside a package.
`id` corresponds to an `_id` index of mongodb.

**Status codes:**

| Code | Rule    |
|------|---------|
| 404 | Specific object not found |
| 400 | Invalid payload |
| 200 | Otherwise |

**Tests:**

1. No package with `id`

Should return a 404 status code.

2. No items matching `name`

Should return a 404 status code.

3. Invalid payload

Should return a 400 status code.

4. Valid new item info

Should return a 200 status code.

**Comment by fchamicapereira** [comment]
You should not change the items by their `name`, but by their `id`.
This should be PUT /items/{id}. The creation of an item is in a specific context. This way we can avoid the creation of items not inserted in any context. After their creation, the modification can be made directly.
The response object is missing its `id`.
