### ISSUE TITLE
DELETE /packages/{id}/items/{id}

### ISSUE THREAD

**Issue by pmx625** [sinfo/deck2#103]
**Path:** /packages/{id}/items/{id}

**Method:** DELETE

**Auth:** COORDINATOR

**Parameters:**

- `id` is a String

**Response:**

```javascript
{
  id: String,
  name: String,
  type: String,
  description: String,
  img: String,
  price: Number // €,
  vat: Number // %
}
```

**Status codes:**

| Code | Rule    |
|------|---------|
| 404 | Company not found |
| 200 | Otherwise |

**Tests:**

1. Package with `id` not found

Should return a 404 status code.

2. Item with `name` not found

Should return a 404 status code.

3. Valid item

Should return the deleted item.

**Comment by fchamicapereira** [comment]
You should remove an item by its `id`, and not by its `name`.
So this should be DELETE /packages/{id}/items/{id}.
Response object is missing its `id`.
