### ISSUE TITLE
GET /items/{id}

### ISSUE THREAD

**Issue by pmx625** [sinfo/deck2#104]
**Path:** /items/{id}

**Method:** GET

**Auth:** MEMBER

**Parameters:**
`id` is a String.

**Response:**

```javascript
{
  id: String,
  name: String,
  type: String,
  description: String,
  img: String,
  price: Number // €,
  vat: Number // %
}
```

**Notes:**
`id` corresponds to an `_id` index of mongodb.
Returns all items by default.

**Status codes:**

| Code | Rule    |
|------|---------|
| 404 | Specific object not found |
| 200 | Always |

**Tests:**

1. No items

Should return a 404 status code.

2. No items matching the `id`

Should return a 404 status code.

3. Item matching the `id`

Should return the matching item.

**Comment by fchamicapereira** [comment]
Response object is missing its `id`.
