### ISSUE TITLE
POST /companies/{id}/participation/package

### ISSUE THREAD

**Issue by pmx625** [sinfo/deck2#108]
**Path:** POST /companies/{id}/participation/package

**Method:** POST

**Auth:** COORDINATOR

**Parameters:**

- `id={String}`

**Payload:**

```javascript
{
  name: String,
  items: [{ item: Item, quantity: Number }],
  price: Number,
  vat: Number
}
```

**Response:**

```javascript
{
  id: String,
  name: String,
  items: [{ item: Item, quantity: Number }],
  price: Number,
  vat: Number
}
```
**Notes:** 
Creates a new package.

**Status codes:**

| Code | Rule    |
|------|---------|
| 400 | Invalid payload |
| 200 | Always |

**Tests:**

1. Missing field on payload
Should return a 400 status code.

2. Invalid field on payload
Should return a 400 status code.

3. Valid payload
Should return the new package.

**Comment by fchamicapereira** [comment]
Again, you create a package in the context of an event (template) or in a company participation.
One of those cases is already taken care of here: https://github.com/sinfo/deck2/issues/74
