### ISSUE TITLE
Meeting Screen infinte loading

### ISSUE THREAD

**Issue by Dpac99** [sinfo/deck2#308]
Meeting screens does not load. Maybe an edge case when there are no meetings?

**Comment by bvlourenco** [comment]
Locally, it works. On the website, I tried checking if there was any error in the browser but it isn't. 
@PMax5 can you see in the backend if there are errors?

**Comment by bvlourenco** [comment]
Solved. The database had "old" meetings and since meetings were changed in backend, this was causing conflicts.
