### ISSUE TITLE
GET /sessions

### ISSUE THREAD

**Issue by fchamicapereira** [sinfo/deck2#51]
**Path:** /sessions

**Method:** GET

**Auth:** member

**Query:**

- `after={Date}` sessions that start after this date
- `before={Date}` sessions that end before this date
- `space={String}` sessions occurring on this space
- `kind={String}` sessions occurring on this space
- `company={String}` sessions registered for this company
- `speaker={String}` sessions registered for this speaker

**Response:**

```javascript
[{
  id: String,
  begin: Date,
  end: Date,
  title: String,
  description: String,
  space: String,
  kind: ['TALK', 'PRESENTATION', 'WORKSHOP'],
  company: Company,
  dinamizers: [{
    name: String,
    position: String,
  }],
  speaker: Speaker,
  videoURL: String
}]
```

**Notes:**

Should return all sessions by default.

**Status codes:**

| Code | Rule    |
|------|---------|
| 400 | Bad query |
| 200 | Always |

**Tests:**

1. No query

Should return all sessions.

2. Before on query

Should return all sessions that start after this date.

3. After on query

Should return all sessions that end before this date.

4. Space on query

Should return all sessions registered on this space.

5. Kind on query

Should return all sessions of this kind.

6. Company on query

Should return all sessions registered for this company.

7. Speaker on query

Should return all sessions registered for this speaker.

8. Bad query

Bad before/bad after: status code 404 on bad date format.

All the others: return empty array.

**Comment by BSDinis** [comment]
Shouldn't you return 400 on bad date format?

**Comment by fchamicapereira** [comment]
I understand the reason why you would think that, but it's just a GET request, doesn't make any changes. On bad date format, just return empty result.
