### ISSUE TITLE
GET /teams

### ISSUE THREAD

**Issue by Dpac99** [sinfo/deck2#56]
**Path:** /teams

**Method:** GET

**Description:**
Gets all teams that match the query. Can be filtered by event, name and member presence

**Auth:** MEMBER

**Query:**
- `event={Event}` Team from this event
- `name={String}` partial match to this name (case insensitive)
- `member={Member}` Contains specified member

**Response:**

```javascript
[{
  id: String
  name: String,
  members: [{
    member: Member, 
    role: ['MEMBER', 'TEAM_LEADER', 'COORDINATOR', 'ADMIN'],
  }],
  meetings: [Meeting]
}]
```
**Notes**
Returns all teams from all editions by default

**Status codes:**

| Code | Rule    |
|------|---------|
| 200 | Always |

**Tests:**

- No query
Should return all teams from all editions.

- `event` on query
Should return an array containig all teams from specified `event`.

- `name` on query
Should return all teams with a partial name case insensitive match to `name`.

- `member` on query:
Should return all teams that specified `member` is or has been a part of

- Bad `event`
Should return an empty array as there are no events that match specified `event`.

- Bad `member`
Should return an empty array as there are no teams that contain specified `member`

**Comment by fchamicapereira** [comment]
You can also filter by member, returning the teams that that member belonged to.
