### ISSUE TITLE
POST /teams

### ISSUE THREAD

**Issue by Dpac99** [sinfo/deck2#57]
**Path:** /teams

**Method:** POST

**Description:**
Adds a new team with `name` to **current** event

**Auth:** COORDINATOR

**Payload:**

```javascript
{
  name: String
}
```

**Response:**

```javascript
{
  id: String
  name: String,
  members: [{
    member: Member, 
    role: ['MEMBER', 'TEAM_LEADER', 'COORDINATOR', 'ADMIN'],
  }],
  meetings: [Meeting]
}
```

**Status codes:**

| Code | Rule    |
|------|---------|
| 400 | Payload missing fields |
| 200 | Otherwise |

**Tests:**

- Missing field on payload
Should return a 400 status code.

- Valid new team info
Should return the new team

**Comment by fchamicapereira** [comment]
Members should not be able to create teams. Coordinator should be the minimum requirement.
