### ISSUE TITLE
PUT /teams/{id}/member

### ISSUE THREAD

**Issue by Dpac99** [sinfo/deck2#58]
**Path:** /teams/{id}/member

**Method:** PUT

**Description:**
Edits role of one or more members of specified team

**Auth:** MEMBER

**Parameters:**

- `id` is a String

**Payload:**

```javascript
[{
  member: Member,
  role:  ['MEMBER', 'TEAM_LEADER', 'COORDINATOR', 'ADMIN']
}]
```

**Response:**

```javascript
{
  id: String
  name: String,
  members: [{
    member: Member, 
    role: ['MEMBER', 'TEAM_LEADER', 'COORDINATOR', 'ADMIN'],
  }],
  meetings: [Meeting]
}
```

**Notes**

`id` corresponds to an `_id` index of mongodb.

**Status codes:**

| Code | Rule    |
|------|---------|
| 400 | Invalid payload |
| 404 | Specific object not found |
| 200 | Otherwise |

**Tests:**

- No team matching the `id`
Should return a 404 status code.

- Invalid member on payload
Should return 400

- Invalid role on payload
Should return 400

- All good
Should return the team with the new role.

**Comment by fchamicapereira** [comment]
Members should not be able to manipulate this data.

**Comment by fchamicapereira** [comment]
And this should be a POST, as you are adding members, and not modifying them

**Comment by Dpac99** [comment]
The idea here is to change a role of an already existing member on the team. But adding a member could be another endpoint
