### ISSUE TITLE
PUT /team/{id}/meeting

### ISSUE THREAD

**Issue by Dpac99** [sinfo/deck2#59]
**Path:** /team/{id}/meeting

**Method:** PUT

**Description:**
Edits one or more meetings of specified team

**Auth:** MEMBER

**Parameters:**

- `id` is a String

**Payload:**

```javascript
[{
  meeting: Meeting
}]
```

**Response:**

```javascript
{
  name: String,
  members: [{
    member: Member, 
    role: ['MEMBER', 'TEAM_LEADER', 'COORDINATOR', 'ADMIN'],
  }],
  meetings: [Meeting]
}
```

**Notes**

`id` corresponds to an `_id` index of mongodb.

**Status codes:**

| Code | Rule    |
|------|---------|
| 400 | Invalid payload |
| 404 | Specific object not found |
| 200 | Otherwise |

**Tests:**

- No team matching the `id`
Should return a 404 status code.

- Invalid meeting on payload
Should return 400

- All good
Should return the team with the new meetings.

**Comment by fchamicapereira** [comment]
This should not exists. This should belong in the /meeting endpoint, creating and adding it to a certain context.
