### ISSUE TITLE
Optimize participations for webapp

### ISSUE THREAD

**Issue by fchamicapereira** [sinfo/deck2#6]
Proposal: insert participations in Event, and store the Speaker inside the Participation

**Comment by BSDinis** [comment]
Elaborate.
What's the common use case you want to optimize?

**Comment by BSDinis** [comment]
pleaze <3

**Comment by fchamicapereira** [comment]
For example, the speaker list on the website. For this info to be retrieved, currently the query fetches all speakers with a participation entry related with the current event.

Optimizing this would be, for example, keeping the participations on the event document

**Comment by BSDinis** [comment]
Could we solve this with and indirection?
Maybe keep a list of announced speakers on the event?

**Comment by fchamicapereira** [comment]
We could, at the cost of redundancy

**Comment by BSDinis** [comment]
Dumb Q: in the end isn't that list of some sort of reference/pointer/indirection to the  objects in the DB?

If not, could we make that so? A bit in the same way some participations have the Event?

Just because this inversion will make the deck (UI) more expensive (dealing with a speaker page would become a nightmare)

**Comment by fchamicapereira** [comment]
The redundancy cost is related to the fact that you said **announced** speakers, specifying a state. The state is the redundant data.

We could keep track of just the speakers with a participation in the current event in the event itself, like an indexer.

**Comment by BSDinis** [comment]
my issue here is the speaker inside the participation seems non-sensical
doesn't your solution involve redundancy as well (the state being having a participation in the event)

the idea of having only the announced is that, while there is redundancy, it is minimized (to strictly solve this optimization problem)

**Comment by fchamicapereira** [comment]
my solution wouldn't lead to redundancy, and I just thought about the trouble of listing all the communications from a specific speaker: it would require a query to all events to acquire the participations, and filter by the speaker

I think your solution is acceptable. As the state machine makes a transition to Announced, that would add an index for the participation in the event

**Comment by BSDinis** [comment]
Ok, will update the schema to reflect this (marked as #issue 6 to signal proposal)
