### ISSUE TITLE
GET /billings

### ISSUE THREAD

**Issue by rodrigdoliveira** [sinfo/deck2#63]
**Path:** /billings

**Method:** GET

**Auth:** member

**Query:**

- ```after={Date}``` billings emitted after this date
- ```before={Date}``` billings emitted before this date
- ```value-greater-than={Number}``` billings with value greather than Number
- ```value-less-than={Number}``` billings with value less than Number
- ```employer={String}``` billings registered for this Employer (CompanyRep.name = String)
- ```event={Event}``` billings registered for companies that participated on this event
- ```company={Company}``` billings registered for this compnay

**Response:**

```javascript
[{
  id: String,
  status: {
    proForma: Boolean,
    invoice: Boolean,
    receipt: Boolean,
    paid: Boolean
  },
  event: Number,
  employer: CompanyRep,
  value: Number, // €
  invoiceNumber: String,
  emission: Date,
  notes: String
}]
```

**Notes:**
Should return all billings by default.

**Status codes:**

| Code | Rule    |
|------|---------|
| 400 | Bad query |
| 200 | Always |

**Tests:**

- No query

Should return all billings

- Before on query

Should return all billings that were emitted before this date

- After on query

Should return all billings that were emitted after this date

- Value-greater-than on query

Should return all billings with value greater than this number

- Value-less-than on query

Should return all billings with value less than this number

- Employer on query

Should return all billings registered for this employer.

- Event on query

Should return all billings registered to companies that participated on the Event

- Company on query

Should return all billings registered for this company

- Bad query

Bad before/bad after: status code 404 on bad date format.
value-greater-than is less than value-less-than: status code 400.

All the others: return empty array.

**Comment by fchamicapereira** [comment]
Add a filter for Companies, that might be useful.

Billings have an ID field.
