### ISSUE TITLE
POST /billings

### ISSUE THREAD

**Issue by rodrigdoliveira** [sinfo/deck2#64]
**Path:** /billings

**Method:** POST

**Auth:** member

**Payload:**

```javascript
{
  status: {
    proForma: Boolean,
    invoice: Boolean,
    receipt: Boolean,
    payed: Boolean
  },
  employer: CompanyRep,
  value: Number, // €
  invoiceNumber: String,
  emission: Date,
  notes: String
}
```

**Response:**

```javascript
{
  id: String,
  status: {
    proForma: Boolean,
    invoice: Boolean,
    receipt: Boolean,
    payed: Boolean
  },
  employer: CompanyRep,
  value: Number,
  invoiceNumber: String,
  emission: Date,
  notes: String
}
```

**Status codes:**

| Code | Rule    |
|------|---------|
| 400 | Invalid payload |
| 200 | Always |

**Tests:**

1. Bad payload

- invalid `emission` date
- no `employer` on payload
- empty invoiceNumber

400 status code

2. All good

Returns new billing.

**Comment by fchamicapereira** [comment]
Billings are created in the context of Companies (for now, it's the only context for them).

Billing objects have an ID field.
