### ISSUE TITLE
PUT /billings/{id}

### ISSUE THREAD

**Issue by rodrigdoliveira** [sinfo/deck2#65]
**Path:** /billings/{id}

**Method:** PUT

**Auth:** member

**Parameters:**
- ```id={String}```

**Payload:**

```javascript
{
  status: {
    proForma: Boolean,
    invoice: Boolean,
    receipt: Boolean,
    paid: Boolean
  },
  event: Number,
  employer: CompanyRep,
  value: Number, // €
  invoiceNumber: String,
  emission: Date,
  notes: String
}
```

**Response:**

```javascript
{
  id: String,
  status: {
    proForma: Boolean,
    invoice: Boolean,
    receipt: Boolean,
    paid: Boolean
  },
  employer: CompanyRep,
  value: Number,
  invoiceNumber: String,
  emission: Date,
  notes: String
}
```

**Status codes:**

| Code | Rule    |
|------|---------|
| 400 | Invalid payload or invalid request |
| 404 | Billing not found |
| 200 | Always |

**Tests:**

1. Bad payload

- invalid `emission` date
- no `employer` on payload
- empty invoiceNumber

400 status code

2. Billing not found

404 status code

3. All good

Returns new billing.

**Comment by fchamicapereira** [comment]
Billings have an ID field.
