### ISSUE TITLE
DELETE /billings/{id}

### ISSUE THREAD

**Issue by rodrigdoliveira** [sinfo/deck2#67]
**Path:** /billings/{id}

**Method:** DELETE

**Auth:** admin

**Parameters:**
- ```id={String}```

**Response:**

```javascript
{
  id: String,
  status: {
    proForma: Boolean,
    invoice: Boolean,
    receipt: Boolean,
    payed: Boolean
  },
  event: Number,
  employer: CompanyRep,
  value: Number,
  invoiceNumber: String,
  emission: Date,
  notes: String
}
```

**Notes:**
```id``` is an ```_id``` field of mongodb.

**Status codes:**

| Code | Rule    |
|------|---------|
| 404 | Billing not found |
| 200 | Always |

**Tests:**

1. No match

404 status code

2. All good

Returns found billing.

**Comment by fchamicapereira** [comment]
Billings have an ID field.
