### ISSUE TITLE
GET /events

### ISSUE THREAD

**Issue by Dpac99** [sinfo/deck2#70]
**Path:** /events

**Method:** GET

**Description:**
Gets all events

**Auth:** MEMBER

**Query:**
- `name={String}` name of event (sinfo27)
- `before={Date}` events that ended before Date
- `after={Date}` events that started after Date
- `during={Date}` took place during this date

**Response:**

```javascript
[{
  name: String,
  begin: Date,
  end: Date,
  themes: [String],
  id: Number,
  teams: [Team],
  packages: [{
    template: Package,
    avaliable: Boolean
  }],
  items: [{
    item: Item,
    avaliable: Number
  }],
  meetings: [Meeting],
  sessions: [Session]
}]
```

**Status codes:**

| Code | Rule    |
|------|---------|
| 400 | Bad Query |
| 200 | Always |

**Tests:**

- No query
Should return an array with all events

- With `name`
Should return an array with all elements that match `name`

- With `before`
Should return an array with all events that ended after `before`

- With `end`
Should return an array with all events that started on `end`

- With `during` 
Should return an array with all events that started before `during` and ended after

- Wrong date format on query
Should return a 400 status code

**Comment by fchamicapereira** [comment]
Events have an ID field.

**Comment by fchamicapereira** [comment]
Add filter for dates (before and after).

**Comment by Dpac99** [comment]
Fixed
