### ISSUE TITLE
POST /events

### ISSUE THREAD

**Issue by Dpac99** [sinfo/deck2#72]
**Path:** /events

**Method:** POST

**Description:**
Creates a new event

**Auth:** COORDINATOR

**Payload:**

```javascript
{
  name: String,
  begin: Date,
  end: Date
}
```

**Notes:**
- `begin` and `end` are optional. `name` is mandatory.

**Response:**

```javascript
{
  name: String,
  begin: Date,
  end: Date,
  themes: [String],
  teams: [Team],
  packages: [{
    template: Package,
    avaliable: Boolean
  }],
  items: [{
    item: Item,
    avaliable: Number
  }],
  meetings: [Meeting],
  sessions: [Session]
}
```

**Status codes:**

| Code | Rule    |
|------|---------|
| 400 | Payload missing fields |
| 200 | Otherwise |

**Tests:**

- Missing `name` on payload
Should return a 400 status code

- Invalid date format
Should return a 400 status code

- Valid info
Should return the new event

**Comment by fchamicapereira** [comment]
You don't need to specify the `id` on the payload. This is automatic (incremental).

**Comment by fchamicapereira** [comment]
Add the option of not specifying the `begin` and `end` on the payload. Most of the times the new event begins, and we don't have yet the specific dates.

**Comment by Dpac99** [comment]
**Edit:**
- Removed id from payload
- Dates are now optional
