### ISSUE TITLE
POST /events/packages

### ISSUE THREAD

**Issue by Dpac99** [sinfo/deck2#74]
**Path:** /events/template

**Method:** POST

**Description:**
Adds new templates to event

**Auth:** COORDINATOR

**Payload:**

```javascript
{
  template: Package,
}
```

**Response:**

```javascript
{
  name: String,
  begin: Date,
  end: Date,
  themes: [String],
  id: Number,
  teams: [Team],
  packages: [{
    template: Package,
    avaliable: Boolean
  }],
  items: [{
    item: Item,
    avaliable: Number
  }],
  meetings: [Meeting],
  sessions: [Session]
}
```

**Notes:**
`id` corresponds to an `_id` index of mongodb.
`avaliable` defaults to true.

**Status codes:**

| Code | Rule    |
|------|---------|
| 400 | Payload missing fields |
| 200 | Otherwise |

**Tests:**

- Missing field on payload
Should return a 400 status code.

- Valid info
Should return the event with the new packages.

**Comment by fchamicapereira** [comment]
Remove the `{id}` from the URL. Only the latest event should be modified.

**Comment by fchamicapereira** [comment]
Modify this URL to be POST /events/template.
This should create only one template, and add it to the array.
The payload should be the package object, and should start by being available.

**Comment by Dpac99** [comment]
**Edit:**
- Renamed endpoint to `/events/template`
- Payload is now a single Package, instead of an array of Packages
