### ISSUE TITLE
POST /events/{id}/teams

### ISSUE THREAD

**Issue by Dpac99** [sinfo/deck2#75]
**Path:** /events/{id}/teams

**Method:** POST

**Description:**
Adds new teams to event

**Auth:** COORDINATOR

**Payload:**

```javascript
{
  teams: [Team]
}
```

**Response:**

```javascript
{
  name: String,
  begin: Date,
  end: Date,
  themes: [String],
  id: Number,
  teams: [Team],
  packages: [{
    template: Package,
    avaliable: Boolean
  }],
  items: [{
    item: Item,
    avaliable: Number
  }],
  meetings: [Meeting],
  sessions: [Session]
}
```

**Notes:**
`id` corresponds to an `_id` index of mongodb.

**Status codes:**

| Code | Rule    |
|------|---------|
| 404 | Specified object not found |
| 400 | Payload missing fields |
| 200 | Otherwise |

**Tests:**

- No event with `id`
Should return a status code 404.

- Missing field on payload
Should return a 400 status code.

- Valid info
Should return the event with the new teams

**Comment by fchamicapereira** [comment]
This doesn't need to exist. The created teams (by POST on /teams) should be added to the current event.

**Comment by Dpac99** [comment]
If the need to add teams to events other than the current one ever emerges, this might be useful. Closing for now then.
