### ISSUE TITLE
PUT /events

### ISSUE THREAD

**Issue by Dpac99** [sinfo/deck2#77]
**Path:** /events

**Method:** PUT

**Description:**
Edits the latest event (name and dates)

**Auth:** COORDINATION

**Payload:**

```javascript
{
  name: String,
  begin: Date,
  end: Date
}
```

**Response:**

```javascript
{
  name: String,
  begin: Date,
  end: Date,
  themes: [String],
  id: Number,
  teams: [Team],
  packages: [{
    template: Package,
    avaliable: Boolean
  }],
  items: [{
    item: Item,
    avaliable: Number
  }],
  meetings: [Meeting],
  sessions: [Session]
}
```

**Notes:**
- `id` corresponds to an `_id` index of mongodb.
- All params on payload are optional, but can't be empty

**Status codes:**

| Code | Rule    |
|------|---------|
| 400 | Payload missing fields |
| 200 | Otherwise |

**Tests:**

- Empty payload
Should return a 400 status code.

- Invalid date format(s)
Should return a 400 status code.

- Valid info
Should return the updated event.

**Comment by fchamicapereira** [comment]
You shouldn't change the id of an event. This is incremental.

**Comment by Dpac99** [comment]
Fixed

**Comment by fchamicapereira** [comment]
Close this: https://github.com/sinfo/deck2/issues/73
Put that functionality here.

**Comment by fchamicapereira** [comment]
Remove the `{id}` form the URL. We should always modify the latest event (none of the information stored by the event should be changed after it occurs).

**Comment by Dpac99** [comment]
**Edit:** 
- Removed {id} from URL.
- Upped the auth level to COORDINATOR
