### ISSUE TITLE
PUT /events/{id}/packages/{name}

### ISSUE THREAD

**Issue by Dpac99** [sinfo/deck2#78]
**Path:** /events/{id}/packages/{name}

**Method:** PUT

**Description:**
Edits avaliability of a package

**Auth:** COORDINATION

**Payload:**

```javascript
{
  avaliable: Boolean
}
```

**Response:**

```javascript
{
  name: String,
  begin: Date,
  end: Date,
  themes: [String],
  id: Number,
  teams: [Team],
  packages: [{
    template: Package,
    avaliable: Boolean
  }],
  items: [{
    item: Item,
    avaliable: Number
  }],
  meetings: [Meeting],
  sessions: [Session]
}
```

**Notes:**
- `id` corresponds to an `_id` index of mongodb.

**Status codes:**

| Code | Rule    |
|------|---------|
| 404 | Specified object not found |
| 400 | Payload missing fields |
| 200 | Otherwise |

**Tests:**

- No event with `id`
Should return a status code 404.

- No package with `name`
Should return a 404 status code.

- Empty payload
Should return a 400 status code.

- Valid info
Should return the event with updated avaliability of specified package.

**Comment by fchamicapereira** [comment]
This is already taken care of here: https://github.com/sinfo/deck2/issues/109
You can close this issue.
