### ISSUE TITLE
PUT /events/{id}/items/{name}

### ISSUE THREAD

**Issue by Dpac99** [sinfo/deck2#79]
**Path:** /events/{id}/items/{name}

**Method:** PUT

**Description:**
Edits number of avaliable items

**Auth:** COORDINATION

**Payload:**

```javascript
{
  avalibale: Number
}
```

**Response:**

```javascript
{
  name: String,
  begin: Date,
  end: Date,
  themes: [String],
  id: Number,
  teams: [Team],
  packages: [{
    template: Package,
    avaliable: Boolean
  }],
  items: [{
    item: Item,
    avaliable: Number
  }],
  meetings: [Meeting],
  sessions: [Session]
}
```

**Notes:**
- `id` corresponds to an `_id` index of mongodb.
- `avaliable` should be equal to or greater than 0

**Status codes:**

| Code | Rule    |
|------|---------|
| 404 | Specified object not found |
| 400 | Payload missing fields |
| 200 | Otherwise |

**Tests:**

- No event with `id`
Should return a status code 404.

- `avaliable` < 0
Should return a 400 status code.

- Payload missing fields
Should return a 400 status code.

- Valid info
Should return the updated event.

**Comment by fchamicapereira** [comment]
This is already taken care of here: https://github.com/sinfo/deck2/issues/102
You can close this issue.
