### ISSUE TITLE
DELETE /events/{id}

### ISSUE THREAD

**Issue by Dpac99** [sinfo/deck2#80]
**Path:** /events/{id}

**Method:** DELETE

**Description:**
Deletes an event.

**Auth:** ADMIN

**Response:**

```javascript
{
  name: String,
  begin: Date,
  end: Date,
  themes: [String],
  id: Number,
  teams: [Team],
  packages: [{
    template: Package,
    avaliable: Boolean
  }],
  items: [{
    item: Item,
    avaliable: Number
  }],
  meetings: [Meeting],
  sessions: [Session]
}
```

**Notes:**
- `id` corresponds to an `_id` index of mongodb.

**Status codes:**

| Code | Rule    |
|------|---------|
| 404 | Specified object not found |
| 200 | Otherwise |

**Tests:**

- No event with `id`
Should return a status code 404.

- Valid info
Should return the deleted event.

**Comment by fchamicapereira** [comment]
Hopefully this will never be used. But good call on creating it. Nice work
