### ISSUE TITLE
GET /contacts

### ISSUE THREAD

**Issue by rodrigdoliveira** [sinfo/deck2#81]
**Path:** /contacts

**Method:** GET

**Auth:** member

**Query:**
- ```phone={String}``` partial match to this phone
- ```mail={String}``` partial match to this mail

**Response:**

```javascript
[{
  id: String,
  phones: [{
    phone: String,
    valid: Boolean
  }],
  socials: {
    facebook: String,
    skype: String,
    github: String,
    twitter: String,
    linkedin: String
  },
  mails: [{
      mail: String,
      personal: Boolean
      valid: Boolean
  }],
}]
```

**Status codes:**

| Code | Rule    |
|------|---------|
| 200 | Always |

**Tests:**

1. No query

Should return all Contacts;

2. Phone on query

Should return all Contacts with a partial phone match to the phone given in the query.

3. Mail on query

Should return all Contacts with a partial mail match to the mail given in the query.

**Comment by fchamicapereira** [comment]
Add filters to this query.

Company has an ID field.
