### ISSUE TITLE
POST /contacts

### ISSUE THREAD

**Issue by rodrigdoliveira** [sinfo/deck2#82]
**Path:** /contacts

**Method:** POST

**Auth:** member

**Payload:**

```javascript
{
  phones: [{
    phone: String,
    valid: Boolean
  }],
  socials: {
    facebook: String,
    skype: String,
    github: String,
    twitter: String,
    linkedin: String
  },
  mails: [{
      mail: String,
      personal: Boolean
      valid: Boolean
  }],
}
```

**Response:**

```javascript
{
  id: String,
  phones: [{
    phone: String,
    valid: Boolean
  }],
  socials: {
    facebook: String,
    skype: String,
    github: String,
    twitter: String,
    linkedin: String
  },
  mails: [{
      mail: String,
      personal: Boolean
      valid: Boolean
  }],
}
```

**Status codes:**

| Code | Rule    |
|------|---------|
| 400 | Invalid payload |
| 200 | Always |

**Tests:**

1. Bad payload
400 status code
2. All good
Returns new contact

**Comment by fchamicapereira** [comment]
You always add Contacts in the context of:
- Speaker
- Company
- CompanyRep
- Member

Contacts not associated with one of the above *should not exist*.

Contact has an ID field.
