### ISSUE TITLE
PUT /contacts/{id}

### ISSUE THREAD

**Issue by rodrigdoliveira** [sinfo/deck2#84]
**Path:** /contacts/{id}

**Method:** PUT

**Auth:** member

**Parameters:**
- ```id={String}```

**Payload:**

```javascript
{
  phones: [{
    phone: String,
    valid: Boolean
  }],
  socials: {
    facebook: String,
    skype: String,
    github: String,
    twitter: String,
    linkedin: String
  },
  mails: [{
      mail: String,
      personal: Boolean
      valid: Boolean
  }],
}
```

**Response:**

```javascript
{
  id: String,
  phones: [{
    phone: String,
    valid: Boolean
  }],
  socials: {
    facebook: String,
    skype: String,
    github: String,
    twitter: String,
    linkedin: String
  },
  mails: [{
      mail: String,
      personal: Boolean
      valid: Boolean
  }],
}
```

**Notes:**
```id``` is an ```_id``` field of mongodb.

**Status codes:**

| Code | Rule    |
|------|---------|
| 400 | Invalid payload or invalid request |
| 404 | Contact not found |
| 200 | Always |

**Tests:**

1. Bad payload

400 status code

2. Contact not found

404 status code

3. All good

Returns new contact.

**Comment by fchamicapereira** [comment]
You can use this method to modify the Contact. If this is the case, then why do all the other PUT/POST endpoints exist?

Contact has an ID field.
