### ISSUE TITLE
POST /contacts/{id}/phones

### ISSUE THREAD

**Issue by rodrigdoliveira** [sinfo/deck2#86]
**Path:** /contacts/{id}/phones

**Method:** POST

**Description:** Add phone to a specific Contact

**Auth:** member

**Parameters:**
- ```id={String}```

**Payload:**

```javascript
{
    phone: String,
    valid: Boolean
}
```

**Response:**

```javascript
{
  id: String,
  phones: [{
    phone: String,
    valid: Boolean
  }],
  socials: {
    facebook: String,
    skype: String,
    github: String,
    twitter: String,
    linkedin: String
  },
  mails: [{
      mail: String,
      personal: Boolean
      valid: Boolean
  }],
}
```

**Notes:**
```id``` is an ```_id``` field of mongodb.

**Status codes:**

| Code | Rule    |
|------|---------|
| 404 | Contact not found |
| 400 | Invalid payload or invalid request |
| 200 | Always |

**Tests:**

1. No match

404 status code

2. Bad payload
- Empty phone string
- Duplicated phone

400 status code

3. All good

Returns modified contact.

**Comment by fchamicapereira** [comment]
Check duplicated phones.
Contact has an ID, missing on the response object.
Test 2 returns the wrong object (should return a Contact object, not a string).
