### ISSUE TITLE
POST /contacts/{id}/mails

### ISSUE THREAD

**Issue by rodrigdoliveira** [sinfo/deck2#87]
**Path:** /contacts/{id}/mails

**Method:** POST

**Description:** Add mail to a specific Contact

**Auth:** member

**Parameters:**
- ```id={String}```

**Payload:**

```javascript
{
    mail: String,
    personal: Boolean
    valid: Boolean
}
```

**Response:**

```javascript
{
  id: String,
  phones: [{
    phone: String,
    valid: Boolean
  }],
  socials: {
    facebook: String,
    skype: String,
    github: String,
    twitter: String,
    linkedin: String
  },
  mails: [{
      mail: String,
      personal: Boolean
      valid: Boolean
  }],
}
```

**Notes:**
```id``` is an ```_id``` field of mongodb.

**Status codes:**

| Code | Rule    |
|------|---------|
| 404 | Contact not found |
| 400 | Invalid payload or invalid request |
| 200 | Always |

**Tests:**

1. No match

404 status code

2. Bad payload
- Empty mail string
- Duplicated mail 

400 status code

3. All good

Returns modified contact.

**Comment by fchamicapereira** [comment]
Contacts have an ID (check response object).

**Comment by fchamicapereira** [comment]
You should check if the mail is not duplicated (error and test).

**Comment by fchamicapereira** [comment]
And the result of the tests are wrong. The response object is a Contact, not an empty email string.
