### ISSUE TITLE
PUT /contacts/{id}/mails/{mail}

### ISSUE THREAD

**Issue by rodrigdoliveira** [sinfo/deck2#88]
**Path:** /contacts/{id}/mails/{mail}

**Method:** PUT

**Description:** Modify specific mail from a specific Contact

**Auth:** member

**Parameters:**
- ```id={String}```
- ```mail={String}```

**Payload:**

```javascript
{
    mail: String,
    personal: Boolean
    valid: Boolean
}
```

**Response:**

```javascript
{
  id: String,
  phones: [{
    phone: String,
    valid: Boolean
  }],
  socials: {
    facebook: String,
    skype: String,
    github: String,
    twitter: String,
    linkedin: String
  },
  mails: [{
      mail: String,
      personal: Boolean
      valid: Boolean
  }],
}
```

**Notes:**
```id``` is an ```_id``` field of mongodb.

**Status codes:**

| Code | Rule    |
|------|---------|
| 404 | Contact not found or ```mail``` not found |
| 400 | Invalid payload or invalid request |
| 200 | Always |

**Tests:**

1. No match

404 status code

2. Bad payload
- Empty mail string
- Duplicated mail 

400 status code

3. All good

Returns modified contact.

**Comment by fchamicapereira** [comment]
Same thing as the other comments.

**Comment by fchamicapereira** [comment]
Contacts have an ID (check response object).
