### ISSUE TITLE
DELETE /contacts/{id}/mails/{mail}

### ISSUE THREAD

**Issue by rodrigdoliveira** [sinfo/deck2#89]
**Path:** /contacts/{id}/mails/{mail}

**Method:** DELETE

**Description:** Delete specific mail from a specific Contact

**Auth:** member

**Parameters:**
- ```id={String}```
- ```mail={String}```

**Response:**

```javascript
{
  id: String,
  phones: [{
    phone: String,
    valid: Boolean
  }],
  socials: {
    facebook: String,
    skype: String,
    github: String,
    twitter: String,
    linkedin: String
  },
  mails: [{
      mail: String,
      personal: Boolean
      valid: Boolean
  }],
}
```

**Notes:**
```id``` is an ```_id``` field of mongodb.

**Status codes:**

| Code | Rule    |
|------|---------|
| 404 | Contact not found or ```mail``` not found |
| 200 | Always |

**Tests:**

1. No match

404 status code

2. All good

Returns modified contact.

**Comment by fchamicapereira** [comment]
Same thing as the phone. Not a mail ID, and fix the tests.

**Comment by fchamicapereira** [comment]
Contacts have an ID (check response object).
