### ISSUE TITLE
PUT /contacts/{id}/phones/{phone}

### ISSUE THREAD

**Issue by rodrigdoliveira** [sinfo/deck2#90]
**Path:** /contacts/{id}/phones/{phone}

**Method:** PUT

**Description:** Modify specific phone from a specific Contact

**Auth:** member

**Parameters:**
- ```id={String}```
- ```phone={String}```

**Payload:**

```javascript
{
    phone: String,
    valid: Boolean
}
```

**Response:**

```javascript
{
  id: String,
  phones: [{
    phone: String,
    valid: Boolean
  }],
  socials: {
    facebook: String,
    skype: String,
    github: String,
    twitter: String,
    linkedin: String
  },
  mails: [{
      mail: String,
      personal: Boolean
      valid: Boolean
  }],
}
```

**Notes:**
```id``` is an ```_id``` field of mongodb.

**Status codes:**

| Code | Rule    |
|------|---------|
| 404 | Contact not found or  ```phone``` not found |
| 400 | Invalid payload or invalid request |
| 200 | Always |

**Tests:**

1. No match

404 status code

2. Bad payload
- Empty phone string
- Duplicated phone

400 status code

3. All good

Returns modified contact.

**Comment by fchamicapereira** [comment]
Contacts don't have a phone ID, they have a phone number (which is a string, check the tests).

**Comment by fchamicapereira** [comment]
Contacts have an ID (check response object).

**Comment by rodrigdoliveira** [comment]
Yes, that's why "phone-id={Number} corresponds to the index of the phones array in this Contact". Empty phone number on tests refers to the phone string you mentioned. Phone-id is a literal index from the phones array from Contact
