### ISSUE TITLE
DELETE /contacts/{id}/phones/{phone}

### ISSUE THREAD

**Issue by rodrigdoliveira** [sinfo/deck2#91]
**Path:** /contacts/{id}/phones/{phone}

**Method:** DELETE

**Description:** Delete specific phone from a specific Contact

**Auth:** member

**Parameters:**
- ```id={String}```
- ```phone={String}```

**Response:**

```javascript
{
   id: String,
   phones: [{
    phone: String,
    valid: Boolean
  }],
  socials: {
    facebook: String,
    skype: String,
    github: String,
    twitter: String,
    linkedin: String
  },
  mails: [{
      mail: String,
      personal: Boolean
      valid: Boolean
  }],
}
```

**Notes:**
```id``` is an ```_id``` field of mongodb.

**Status codes:**

| Code | Rule    |
|------|---------|
| 404 | Contact not found or ```phone``` not found |
| 200 | Always |

**Tests:**

1. No match

404 status code

2. All good

Returns modified contact.

**Comment by fchamicapereira** [comment]
Contacts don't have a phone ID, they have just a phone number.

**Comment by fchamicapereira** [comment]
And phones are not numbers, are strings (check the tests).

**Comment by fchamicapereira** [comment]
Contacts have an ID (check response object).
