### ISSUE TITLE
GET /meetings

### ISSUE THREAD

**Issue by Stramer1** [sinfo/deck2#96]
**Path:**  /meetings

**Method:** GET 

**Description:** Gets a list of meetings

**Auth:** member

**Query:**

- `event={Event}` meetings of this event. If empty gives all events;
- `team={Team}` meetings from a specific team. If empty gives general meetings.
- `company={Company}` meetings with a specific company. (company of a companyRep)

**Response:**

```javascript
[{
  id: String
  begin: Date,
  end: Date,
  place: String,
  minute: String, // aka ata
  participants: { members: [Member], companyReps: [CompanyRep] }
}]
```

**Status codes:**

| Code | Rule   |
|------|--------|
| 200  | Always |

**Tests:**

1. No query
    * Should return all meetings;

2. Query with event specified
3. Query with team specified
4. Query with company specified
    * Should return all meetings of the specified parameter

5. Query with event, team and company specified
    * Should return all meetings of the specified event, team and company 

6. Query with invalid Event
7. Query with invalid Team
8. Query with invalid Company
    * Should return empty array

**Comment by fchamicapereira** [comment]
Add date filters (after and/or before some date).
You don't need to specify the "unauthorized access" error (it's not specified in any of the other endpoints).
