### ISSUE TITLE
POST /meetings

### ISSUE THREAD

**Issue by Stramer1** [sinfo/deck2#97]
**Path:** /meetings

**Method:** POST 

**Auth:** member

**Payload:**

```javascript
{
  team: Team, (optional)
  thread: Thread, (optional)
  begin: Date,
  end: Date, (optional)
  place: String, (optional)
  minute: String, // aka ata (optional)
  participants: { members: [Member], companyReps: [CompanyRep] } (optional)
}
```
**Response:**

```javascript
{
  id: String
  begin: Date,
  end: Date,
  place: String,
  minute: String, // aka ata
  participants: { members: [Member], companyReps: [CompanyRep] }
}
```
**Status codes:**

| Code | Rule |
|------|------|
| 401  | Unauthorized access |
| 400  | Invalid begin date, end date, participants, team or thread |
| 201  | Otherwise |

**Tests:**

1. Unauthorized access
    * Should return 401

2. Meeting with end date < begin date
4. Meeting with invalid participant
5. Meeting with invalid team
6. Meeting with invalid thread
7. Meeting with both team and thread
    * Should return 400

8. Simple meeting (without optional fields)
9. Simple meeting with team
10. Simple meeting with thread
11. Meeting with place, minute and participants
    * Should return the created meeting

**Comment by fchamicapereira** [comment]
This should not exist.
We are taking another approach for this feature.
Some examples: https://github.com/sinfo/deck2/issues/95, https://github.com/sinfo/deck2/issues/92, https://github.com/sinfo/deck2/issues/95

This means that every object that should not be created without a context (for example, a Billing, a Meeting, Contact, etc.) should be created in that specific context.

In your case, a meeting is created in an Event (if it is a SINFO's meeting), or in a Team (if it is a team meeting), or in a Thread (if it is a meeting with a specific company).

You can close this issue and create others that reflect this.
