### ISSUE TITLE
PUT /meetings/{id}

### ISSUE THREAD

**Issue by Stramer1** [sinfo/deck2#98]
**Path:** /meetings/{id}

**Method:** PUT

**Description:** Changes a meeting

**Auth:** member

**Params:**
- `id` is a string

**Payload:**

```javascript
{
  begin: Date,
  end: Date, (optional)
  place: String, (optional)
  minute: String, // aka ata (optional)
  participants: { members: [Member], companyReps: [CompanyRep] } (optional)
}
```
**Response:**

```javascript
{
  id: String
  begin: Date,
  end: Date,
  place: String,
  minute: String, // aka ata
  participants: { members: [Member], companyReps: [CompanyRep] }
}
```
**Status codes:**

| Code | Rule |
|------|------|
| 404  | Id not found |
| 400  | Invalid begin date, end date or participant |
| 201  | Otherwise |

**Tests:**

1. Id not found
    * Should return 404

2. Meeting with invalid end date
3. Meeting with invalid begin date
4. Meeting with invalid participant
    * Should return 400

5. Simple meeting (without optional fields)
6. Meeting with place, minute and participants
    * Should return the created meeting

**Comment by fchamicapereira** [comment]
The payload is wrong. You should modify only the fields of the Meeting, except for the participants. The participants (members and companyReps) should have their own POST and DELETE requests for adding and removing from the array, respectively.
