### ISSUE TITLE
DELETE /events/meeting/{id}

### ISSUE THREAD

**Issue by Stramer1** [sinfo/deck2#99]
**Path:** /events/meeting/{id}

**Method:** DELETE

**Description:** Deletes a meeting from the current event

**Auth:** member

**Params:**
- `id` is a string

**Response:**

```javascript
[{
  id: String
  begin: Date,
  end: Date,
  place: String,
  minute: String, // aka ata
  participants: { members: [Member], companyReps: [CompanyRep] }
}]
```

**Status codes:**

| Code | Rule            |
|------|--------------|
| 404  | id not found |
| 200  | Otherwise |

**Tests:**

1. id not found
    * Should return 404
2. Valid id
    * Should return deleted meeting

**Comment by fchamicapereira** [comment]
I think this shouldn't exists. The argument would be that if a Meeting only exists in a certain context, being able to delete the meeting would require a search for the entity that is the context of this meeting, be it an Event, Company or Team. That will be a heavy query.

The counter proposal is the following: when a DELETE request for a meeting in the event is called, that meeting will be deleted. The same goes for the thread and company.
